// Category Icons Index
export const automobile = require('./categoryIcons/automobile.webp');
export const breakingNews = require('./categoryIcons/breaking news.webp');
export const business = require('./categoryIcons/business.webp');
export const curatedForYou = require('./categoryIcons/Curated for you.webp');
export const curatedForYouAlt = require('./categoryIcons/curatedForYou.webp');
export const entertainment = require('./categoryIcons/entertainment.webp');
export const health = require('./categoryIcons/health.webp');
export const internationalNews = require('./categoryIcons/international News.webp');
export const lifestyle = require('./categoryIcons/lifestyle.webp');
export const opinions = require('./categoryIcons/opinions.webp');
export const politics = require('./categoryIcons/politics.webp');
export const science = require('./categoryIcons/science.webp');
export const sports = require('./categoryIcons/sports.webp');
export const startup = require('./categoryIcons/startup.webp');
export const travel = require('./categoryIcons/travel.webp');
export const world = require('./categoryIcons/world.webp');
export const technology = require('./categoryIcons/technology.webp');
export const finance = require('./categoryIcons/finance.webp');